version: "3.8"

networks:
  wirehole_network:
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/16

services:

  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: unless-stopped
    hostname: unbound
    networks:
      wirehole_network:
        ipv4_address: ${UnboundIP}

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: ${TimeZone}
      PIHOLE_DNS_: ${UnboundIP};${UnboundIP} # Must be twice
      WEBPASSWORD: ${PiHolePassword}
      ServerIP: ${WireguardIP}
      DNSMASQ_LISTENING: local
    volumes:
      - "./cache/etc-pihole/:/etc/pihole/"
      - "./cache/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    network_mode: service:wireguard-ui

  wireguard-ui:
    depends_on: [unbound]
    container_name: wireguard-ui
    image: weejewel/wg-easy
    restart: unless-stopped
    env_file: .env
    environment:
      WG_HOST: ${PublicIP}
      PASSWORD: ${WireguardPassword}
      WG_PORT: 51820
      WG_DEFAULT_ADDRESS: 10.10.10.x
      WG_DEFAULT_DNS: ${WireguardIP}, ${WireguardIP}
      WG_ALLOWED_IPS: 0.0.0.0/0, ::0/0
    volumes:
      - "./cache/etc-wireguard:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51810:51821/tcp" # Web-interface
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    hostname: wirehole
    dns:
      - ${WireguardIP} # Pi-hole
      - ${UnboundIP}
    networks:
      wirehole_network:
        ipv4_address: ${WireguardIP}
